name: Python Code Quality
on:
  push:
    branches: [main]
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv lock --locked

  linting:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check .

  build-docker:
    runs-on: ubuntu-latest
    needs: [linting]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: docker build -t myapp:latest .
      - name: Save Docker image
        run: docker save myapp:latest -o myapp.tar
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-latest
          path: myapp.tar

  build:
    runs-on: ubuntu-latest
    needs: [linting]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv build
      - name: Get version
        id: version
        run: echo "version=$(uv run python -c "import sys; sys.path.insert(0, '.'); from src import __version__; print(__version__)")" >> $GITHUB_OUTPUT
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ steps.version.outputs.version }}
          path: dist/
